### ISSUE TITLE
Skin signature?

### ISSUE THREAD

**Issue by DoNotSpamPls** [Electroid/mojang-api#15]
Is there any way to get the signature of a player's skin using your API? (since the Minecraft client doesn't accept skins without the signature)

~~P.S. I just noticed that that the keys for the cape and the skin are the same - wouldn't that be a problem? (and also a bit of a violation of RFC7159)~~

**Comment by Electroid** [comment]
Not currently, but that's a great idea and a pretty simple addition! I'm also not sure what you mean by the same keys? There's `skin: {}` and `cape: {}`.

**Comment by DoNotSpamPls** [comment]
Well, this is what happens when I try to code at 1AM ;-;. Thanks for pointing out. I'm eagerly waiting for the feature :stuck_out_tongue:

**Comment by xkuyax** [comment]
Hey, @Electroid nice api you built! What is the current status of including the signature? I would like  to use your api in production, but this feature is still missing, so we have to call mojang by ourself.

**Comment by xkuyax** [comment]
Okay great! Do you have a rough time estimate?

**Comment by Electroid** [comment]
It's almost production-ready! (not quite yet) I'll merge the code on Github and announce when you can trust it will be online.

Example: https://api.ashcon.app/mojang/v2/user/Dinnerbone

**Comment by xkuyax** [comment]
Thanks a lot!
Looks good :)

**Comment by Leymooo** [comment]
Thanks for add adding signature, but why it spend a lot of time for first request? ~3-4secs. Maybe this caused by "textures"."skin"."data'? If yes, how about to add a new route, those will only provide `name`, `uuid`, skin `value` and skin `signature`?.

**Comment by Electroid** [comment]
Due to some Cloudflare issues and the 3 second initial delay, I'm working on `v2` again but it will be experiencing downtime. Sorry for the wait, school work tends to pill up these days!

**Comment by DoNotSpamPls** [comment]
Any progress on this?

**Comment by Electroid** [comment]
Interestingly, I'm interning at Cloudflare right now (and on the Workers Storage team). If I find some time outside of work I will make some progress!

**Comment by Electroid** [comment]
Looks like that time has come! The `textures.raw` field is now GA and live in `v2` - 17a2438aaf136189dee821f0cf128508167fa7d5

**Comment by Electroid** [comment]
@DoNotSpamPls @xkuyax @Leymooo Feel free to start using `v2` in production! (It's also fast!!)
