### ISSUE TITLE
Account creation date?

### ISSUE THREAD

**Issue by h1rule** [Electroid/mojang-api#16]
Is there a way to get the time when the account was created through this API?

**Comment by Electroid** [comment]
I don't believe Mojang publishes this information publicly, if you know a place where I can find it, please mention and I can include it!

**Comment by Electroid** [comment]
@h1rule Looks like this is [technically possible](https://gist.github.com/jomo/be7dbb5228187edbb993) but I will need to evaluate whether it is technically feasible with Cloudflare's request restrictions.

**Comment by Electroid** [comment]
I'll be adding a `created_at: <date>` field in `v2`. Unfortunately, if the account has name changes or is legacy, it will not work, so will show `null`. This will be merged and deployed early this week!

**Comment by Electroid** [comment]
The `created_at` field is now GA and live in `v2` - 17a2438aaf136189dee821f0cf128508167fa7d5

**Comment by Electroid** [comment]
Just to notify you can trust to use it in production! @h1rule
