### ISSUE TITLE
API not available

### ISSUE THREAD

**Issue by xkuyax** [Electroid/mojang-api#17]
Hi, your link does no longer work?

https://api.ashcon.app/mojang/v1/user/ElectroidFilms
Returns 404 from Github Pages

**Comment by talle117** [comment]
There was recently an issue with Cloudflare's load balances for some of their customers only a few hours ago. This may be a cause of the API returning a 404.

**Comment by xkuyax** [comment]
> There was recently an issue with Cloudflare's load balances for some of their customers only a few hours ago. This may be a cause of the API returning a 404.

api.ashcon.app is github.io site (i think?) and github is returning the 404, so there is a problem with his site? (i think, not really sure)

**Comment by Electroid** [comment]
@xkuyax @talle117 For some reason, the Cloudflare Worker's Route was disabled. I manually re-enabled them and urgently contacted their support! (It's been back up for several hours)
