### ISSUE TITLE
 v2 returns invalid error codes

### ISSUE THREAD

**Issue by MrZillaGold** [Electroid/mojang-api#28]
If we reach the set limit for obtaining information for a certain period of time, v2 api returns 404 instead of 429, in v1 everything is fine

![image](https://user-images.githubusercontent.com/42776347/82980331-89418880-a02c-11ea-9ef6-93ee175a6b1f.png)
![image](https://user-images.githubusercontent.com/42776347/82980376-aa09de00-a02c-11ea-871a-f14879b66be2.png)

**Comment by Electroid** [comment]
Thanks will investigate.

**Comment by MrZillaGold** [comment]
This happens with absolutely all errors.

**Comment by andreasdc** [comment]
> Thanks will investigate.

Will be nice to get this fixed, this api is almost non usable, because of that.

**Comment by andreasdc** [comment]
> Thanks will investigate.

Currently mojang is down and your api shows users as offline.

**Comment by andreasdc** [comment]
{
  "code": 404,
  "error": "Not Found",
  "reason": "No user with the name 'test' was found"
}

**Comment by Electroid** [comment]
Sorry this took so long, fixed in https://github.com/Electroid/mojang-api/commit/991e1e9850220cf2124a2d7a7375b52385507ea3

**Comment by andreasdc** [comment]
> Sorry this took so long, fixed in [991e1e9](https://github.com/Electroid/mojang-api/commit/991e1e9850220cf2124a2d7a7375b52385507ea3)

Too long :D
