### ISSUE TITLE
Invalid response when mojang api is down.

### ISSUE THREAD

**Issue by makindotcc** [Electroid/mojang-api#35]
Hello. A moment ago the mojang api was down for a moment and then request to the ``https://api.ashcon.app/mojang/v2/user/www_makin_CC`` url was returning ``No user with the name 'www_makin_CC' was found`` which is not true. I don't understand coffee code too much, but if im right your api will always respond with this message if mojang returns an error.
https://github.com/Electroid/mojang-api/blob/aff20321e3a1d78f1a3dfae404013127388ea4b0/src/api.coffee#L5-L17

**Comment by Electroid** [comment]
Thanks for flagging this, same issue as #28. Working on a fix.
