### ISSUE TITLE
Random 404 errors for people that exist

### ISSUE THREAD

**Issue by ImPlotzes** [Electroid/mojang-api#40]
Recently I've noticed that I will sometimes get a 404 error when searching a player that does exist. The weird thing is that when I search the same player a few minutes later it will work as normal. I can't seem to find a pattern so I'm not sure what it could be. 

![image](https://user-images.githubusercontent.com/47643346/113415512-a5862280-93bf-11eb-9ca8-1ed720187adc.png)

**Comment by MrZillaGold** [comment]
This may be due to this problem: https://github.com/Electroid/mojang-api/issues/28

If this happens again, try making a request to version 1 of the API and see the error code.

**Comment by ImPlotzes** [comment]
How do I change the version?

**Comment by ImPlotzes** [comment]
> This may be due to this problem: #28
> 
> If this happens again, try making a request to version 1 of the API and see the error code.

I've been using the v1 API, and I haven't been getting weird 404 errors, but I sometimes get 429 - Too many requests. This is kinda weird to me since I thought this service was caching results and so you wouldn't need to cache the results on your own. It is especially weird to me since I can get a 429 result when my last call was over 30 mins ago...

**Comment by MrZillaGold** [comment]
I have also noticed recently that the restrictions have become a bit strict, with a small number of requests, you can run into rate limit.

**Comment by harvanchik** [comment]
I've also noticed that other sites that call the Mojang API are having issues too.

**Comment by Electroid** [comment]
Mojang likes changing things without notice, so I will revisit the caching TTL and fix the miscategorization of the 429 errors. Sorry some of y'all have downgraded to `v1` to avoid this; not ideal. Will prioritize this.

**Comment by Electroid** [comment]
Fixed
