### ISSUE TITLE
3 lettered usernames, at some points in time, do not exist according to Ashcon.

### ISSUE THREAD

**Issue by business-goose** [Electroid/mojang-api#42]
Proof that Mojang API does in-fact say my username is "G6_" [Click here to test it for yourself](https://sessionserver.mojang.com/session/minecraft/profile/a52f1f08a398400abca42b74b81feae6?unsigned=false)
![image](https://user-images.githubusercontent.com/44676012/116821887-c20aab80-ab73-11eb-87e5-6b35c8a77836.png)

Proof that Ashcon doesn't believe my username is "G6_" [Click here to test it for yourself, results will change](https://api.ashcon.app/mojang/v2/user/G6_)
![image](https://user-images.githubusercontent.com/44676012/116821938-19a91700-ab74-11eb-875f-6199cf267830.png)

I'm not sure what calls these "flare ups", but at the moment it doesn't seem as if there is one at the present moment. If I notice one, I'll notify you here.
Last one I noticed was on the 2nd of May, 2021

**Comment by harvanchik** [comment]
I think this is a problem in general and has no relation to the length of the username.  I noticed that other website that use the Mojang API are also getting 404 errors.  For example, [Minotar](https://minotar.net/) is one of those.

**Comment by business-goose** [comment]
> I think this is a problem in general and has no relation to the length of the username. I noticed that other website that use the Mojang API are also getting 404 errors. For example, [Minotar](https://minotar.net/) is one of those.

Hmm, that's interesting. For some reason the main Mojang API doesn't seem to be encountering errors, perhaps it's some form of new ratelimiting?

**Comment by harvanchik** [comment]
> Hmm, that's interesting. For some reason the main Mojang API doesn't seem to be encountering errors, perhaps it's some form of new ratelimiting?

It's not the Mojang API that is the problem.  It is how these third party services are calling the API.  I have no idea what changed, but it could be a new form of rate limiting.

**Comment by xknat** [comment]
Issue seems to be resolved after contacting the dev.

**Comment by business-goose** [comment]
Closing this.
