### ISSUE TITLE
Mojang no longer lets users look up usernames at time

### ISSUE THREAD

**Issue by MisterFixx** [Electroid/mojang-api#43]
https://bugs.mojang.com/browse/WEB-3367
As usual, it looks like Mojang silently dropped support for this and are not planning to return it (like they did with many other JSON API related features 🙄).

This causes the account creation estimates in the response to either be null or inaccurate at all.
seeing as Mojang will most likely not fix this, it's probably for the best to just remove account creation estimates.

**Comment by Electroid** [comment]
I know, it's a shame they decided to remove it. Going forward, new users will have a `null` birthday, but any that are cached will continue to stay.
