### ISSUE TITLE
API temporarily responding with bad status (update: fixed)

### ISSUE THREAD

**Issue by Janmm14** [Electroid/mojang-api#47]
Returns 404 for every request.

Maybe related to some previous upstream problem and bad results got cached?

**Comment by harvanchik** [comment]
Seems like a Mojang/Minecraft thing. https://mojangstat.us/
[Minotar](https://minotar.net/helm/flashee/32.png) also not working.

**Comment by Janmm14** [comment]
The session server is not down for me although the status tells that

For example
https://sessionserver.mojang.com/session/minecraft/profile/4566e69fc90748ee8d71d7ba5aa00d20
is reachable and answers normally

**Comment by harvanchik** [comment]
My best guess is that Mojang changed something in the API then.

**Comment by MisterFixx** [comment]
https://mc-heads.net/mcstatus
Everything seems fine with Mojang

**Comment by Electroid** [comment]
Hi, investigating. Sorry for the delay

**Comment by Electroid** [comment]
Looks like requests to Mojang are failing with the `525` status code. There seems to be some SSL issue.

**Comment by Electroid** [comment]
Update: still investigating, the issue is known, now finding out why this is happening.

**Comment by Electroid** [comment]
Update: Cloudflare engineers are looking at it. It appears there is an issue with the SSL certificate. This is affecting all requests to `*.mojang.com` from Cloudflare, so there isn't a quick-fix. Will update again soon.

**Comment by Electroid** [comment]
Update: fixed. Cloudflare has a "flexible" SSL mode, which started to cause errors with Mojang's SSL certificate. The root cause is still being investigated by them, but the API should be back up. Apologies for the disruption.

**Comment by MisterFixx** [comment]
I'm running something similar to this repo which also makes requests to Mojang's API but I'm still seeing a whole lot of 525 errors, is there something i need to do to fix this?
