### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by andreasdc** [Electroid/mojang-api#48]
Wouldn't it be faster to make 1 url just for uuid?

**Comment by sadcenter** [comment]
How would it be faster? There is a check if a username or uuid was given, and if username - it first searches for uuid by username and then find anything else

**Comment by harvanchik** [comment]
Yeah, an if-else statement is not going to make it slower.  See https://github.com/Electroid/mojang-api/blob/master/src/api.coffee#L24.

**Comment by andreasdc** [comment]
> How would it be faster? There is a check if a username or uuid was given, and if username - it first searches for uuid by username and then find anything else

You have textures and signature in the same link.

**Comment by harvanchik** [comment]
> > How would it be faster? There is a check if a username or uuid was given, and if username - it first searches for uuid by username and then find anything else
> 
> You have textures and signature in the same link. And it often works slower than Mojang's url.

This is the wrong API for you then.  This API is for getting all the the information in one request rather than multiple.  It will be slower that way.

**Comment by andreasdc** [comment]
> > > How would it be faster? There is a check if a username or uuid was given, and if username - it first searches for uuid by username and then find anything else
> > 
> > 
> > You have textures and signature in the same link. And it often works slower than Mojang's url.
> 
> This is the wrong API for you then. This API is for getting all the the information in one request rather than multiple. It will be slower that way.

But it has no rate limits right?

**Comment by Electroid** [comment]
I could add some query parameters, or another endpoint to configure what you want/don't want. That should make it faster depending on your exact needs (say, if you don't need textures)

**Comment by harvanchik** [comment]
> I could add some query parameters, or another endpoint to configure what you want/don't want. That should make it faster depending on your exact needs (say, if you don't need textures)

That's a great idea actually.

**Comment by andreasdc** [comment]
> I could add some query parameters, or another endpoint to configure what you want/don't want. That should make it faster depending on your exact needs (say, if you don't need textures)

Sounds cool, your api doesn't have rate limits right? Also could you look into this issue? https://github.com/Electroid/mojang-api/issues/49

**Comment by sadcenter** [comment]
> I could add some query parameters, or another endpoint to configure what you want/don't want. That should make it faster depending on your exact needs (say, if you don't need textures)

Yea, that would be very useful for me. I'm writing my own implementation of mojang authlib and want to use your API because timings are nice but your API provides too much data (more data-> gson takes more time to deserialize). I just need textures from username for instance.

**Comment by andreasdc** [comment]
> I could add some query parameters, or another endpoint to configure what you want/don't want. That should make it faster depending on your exact needs (say, if you don't need textures)

Is mojang/v2/uuid safe to use to just get uuid of premium player? Please check this issue too https://github.com/Electroid/mojang-api/issues/49

**Comment by Electroid** [comment]
You can use: https://api.ashcon.app/mojang/v2/uuid/Notch to just get the UUID.

**Comment by andreasdc** [comment]
> You can use: https://api.ashcon.app/mojang/v2/uuid/Notch to just get the UUID.

I see it returns normal 404 http response code in my java app, am I right? It returns 404 when player is offline mode, right?
