### ISSUE TITLE
Connection Timeouts

### ISSUE THREAD

**Issue by Zeryther** [Electroid/mojang-api#50]
Hi, I'm currently receiving occasional connection timeouts when trying to ping the API. Anybody know what's going on?

![image](https://user-images.githubusercontent.com/5731334/142631503-3aa04d3f-8fa8-4d41-b4f8-acdb2a189ef2.png)

Thanks

**Comment by MisterFixx** [comment]
You can always clone it and host it yourself

**Comment by Zeryther** [comment]
> You can always clone it and host it yourself

Thanks, but that's not the issue here. The API seems to not be working and I would like to let @Electroid know. Not trying to force a quick fix as I know this API is a free, open-source product, but I think I should still let people know of status problems. I have asked other people to test the API out and it doesn't seem to be a problem on my end.

**Comment by harvanchik** [comment]
It's back up, or at least it's working for me.

**Comment by Electroid** [comment]
Thanks for the notification, very strange. Looking into it.
