### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by andreasdc** [Electroid/mojang-api#51]
I often get bad results, premium users are authenticated as no-premium. What's going on?

**Comment by Dymeth** [comment]
Related with #53?

**Comment by MrZillaGold** [comment]
https://github.com/Electroid/mojang-api/issues/28

**Comment by Electroid** [comment]
Fixed in https://github.com/Electroid/mojang-api/commit/991e1e9850220cf2124a2d7a7375b52385507ea3
