### ISSUE TITLE
Signature missing on some request

### ISSUE THREAD

**Issue by xknat** [Electroid/mojang-api#52]
API seems to have been missing signature some request recently
https://api.ashcon.app/mojang/v2/user/srteam --> https://pastebin.com/SY9yn5L1
https://api.ashcon.app/mojang/v2/user/xknat --> https://pastebin.com/cLbkgPpH
Notice how the signature part is completely gone

https://sessionserver.mojang.com/session/minecraft/profile/7dcfc130-344a-4719-9fbe-3176bc2075c6?unsigned=false still works.

**Comment by pikachub2005** [comment]
> https://pastebin.com/SY9yn5L1 
> https://pastebin.com/cLbkgPpH

Those don't work...

**Comment by pikachub2005** [comment]
> API seems to have been missing signature some request recently https://api.ashcon.app/mojang/v2/user/srteam --> https://pastebin.com/SY9yn5L1 https://api.ashcon.app/mojang/v2/user/xknat --> https://pastebin.com/cLbkgPpH Notice how the signature part is completely gone
> 
> https://sessionserver.mojang.com/session/minecraft/profile/7dcfc130-344a-4719-9fbe-3176bc2075c6?unsigned=false still works.

Seems to be working now...

**Comment by pikachub2005** [comment]
BTW what is the signature for

**Comment by xknat** [comment]
https://wiki.vg/Mojang_API#UUID_to_Profile_and_Skin.2FCape

**Comment by pikachub2005** [comment]
Still don't understand but thanks =/

**Comment by Electroid** [comment]
This is probably a transient issue. Feel free to re-open if you have some reproducible examples.

**Comment by xknat** [comment]
Ah yes sorry, this could be closed, no longer a issue.
Did not hear any more cases of this happening
