### ISSUE TITLE
A LOT of false positives

### ISSUE THREAD

**Issue by andreasdc** [Electroid/mojang-api#53]
There are a lot of false positives nowadays, can you check what is going on? Is there a way to prevent this or detect the error?

**Comment by Electroid** [comment]
What do you mean by false positive? Is this for the birthdays or just status codes in genera?

**Comment by Dymeth** [comment]
I confirm this issue. With a large number of consecutive requests for a while, the api begins to return information that some premium accounts doesn't exists

**Comment by Dymeth** [comment]
Also possibly related with #40 or #28

**Comment by andreasdc** [comment]
@Electroid are there any updates on that?

**Comment by Dymeth** [comment]
> @Electroid are there any updates on that?

Looks like it's fixed now
