### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by andreasdc** [Electroid/mojang-api#54]
Is error 404 intentional when calling from java for no-premium players?

**Comment by harvanchik** [comment]
If by no-premium members you mean people who have not purchased the game, then they don't exist in the Mojang database -- hence the 404 (not found) error.

**Comment by andreasdc** [comment]
> If by "no-premium players" you mean people who have not purchased Minecraft, then they don't exist in the Mojang database -- hence the 404 (not found) error.

Also it shows 404 for premium players...

**Comment by MrZillaGold** [comment]
https://github.com/Electroid/mojang-api/issues/28

**Comment by Electroid** [comment]
Fixed in https://github.com/Electroid/mojang-api/commit/991e1e9850220cf2124a2d7a7375b52385507ea3
