### ISSUE TITLE
Increased amount of 429 errors

### ISSUE THREAD

**Issue by ciulinuwu** [Electroid/mojang-api#61]
### Brief Description
User endpoint appears to stop working at random intervals.
[https://api.ashcon.app/mojang/v2/user/ciulinuwu](https://api.ashcon.app/mojang/v2/user/ciulinuwu) returns a 404 response:
```json
{
  "code": 404,
  "error": "Not Found",
  "reason": "No user with the UUID '4a9ce7bb585c4ddb96749c8f0b845ea7' was found"
}
```

**Comment by ciulinuwu** [comment]
As of posting this, API functionality has returned.

Closing this issue.

**Comment by Electroid** [comment]
Hi, this is being investigated. It appears to be a change in rate-limiting from Mojang.

**Comment by Electroid** [comment]
Hi everyone. I've just committed and deployed https://github.com/Electroid/mojang-api/commit/991e1e9850220cf2124a2d7a7375b52385507ea3 which will pass the original HTTP status instead of always showing `400` whenever there is an issue.

It appears Mojang has made their rate limiting more aggressive. I'm working on a longer term fix to reduce the `429` errors. In the mean time, I've increased the cache TTL to reduce these errors. Will keep you all updated.

**Comment by andreasdc** [comment]
What does 'more aggressive' rate limiting means?

**Comment by AoElite** [comment]
Do you happen to know what these new mojang rate limits are?

**Comment by eyezahhhh** [comment]
I've just started getting
```json
{
   "code":429,
   "error":"Too Many Requests",
   "reason":"You are sending too many requests."
}
```
Is this the same issue? (as in a Mojang rate limit as opposed to a Cloudflare rate limit from this API)

**Comment by Fejm** [comment]
Can we just get lightweight version of API? Ex. just getting UUID from name? I think current API just do to much and it's being rate limited.

**Comment by Electroid** [comment]
> Can we just get lightweight version of API? Ex. just getting UUID from name? I think current API just do to much and it's being rate limited.

If you just need the UUID, you can use: https://api.ashcon.app/mojang/v2/uuid/Notch

**Comment by AoElite** [comment]
@Electroid 

> > Can we just get lightweight version of API? Ex. just getting UUID from name? I think current API just do to much and it's being rate limited.
> 
> If you just need the UUID, you can use: https://api.ashcon.app/mojang/v2/uuid/Notch

I think you should mention this in the readme because I don't think a lot of people know about it. It could help with rate limiting.

**Comment by xRyann2255** [comment]
> > Can we just get lightweight version of API? Ex. just getting UUID from name? I think current API just do to much and it's being rate limited.
> 
> If you just need the UUID, you can use: https://api.ashcon.app/mojang/v2/uuid/Notch

Is there a similar endpoint which only returns the username from uuid?

**Comment by xRyann2255** [comment]
> Hi everyone. I've just committed and deployed [991e1e9](https://github.com/Electroid/mojang-api/commit/991e1e9850220cf2124a2d7a7375b52385507ea3) which will pass the original HTTP status instead of always showing `400` whenever there is an issue.
> 
> It appears Mojang has made their rate limiting more aggressive. I'm working on a longer term fix to reduce the `429` errors. In the mean time, I've increased the cache TTL to reduce these errors. Will keep you all updated.

Any updates on this?

**Comment by kyngs** [comment]
Hi, the API now appears not to accept any requests at all:
```json
{
  "code": 429,
  "error": "Too Many Requests",
  "reason": "Failed to find user with the name 'kyngs'"
}
```

**Comment by andreasdc** [comment]
This update ruined all cloudflare workers connection to mojang.

**Comment by andreasdc** [comment]
I recommend disabling repo for some time and make a fix.

**Comment by Electroid** [comment]
The reason for the increased `429`s actually appears to be because someone is sending 60 million requests per day, hogging up the rate limits. (this is way way above anyone else)

I've limited the IP, so errors should start to reduce.

**Comment by andreasdc** [comment]
For me even the original api returns for online mode players weird uuid and name "null", did something change? When I check https://api.mojang.com/users/profiles/minecraft/asdasdas12321
there is 
`{
  "path" : "/users/profiles/minecraft/asdasdas12321",
  "errorMessage" : "Couldn't find any profile with that name"
}`
which is different to what I see on the server.

**Comment by andreasdc** [comment]
I think it's good to control such movements, because it blocks whole traffic on all workers.

**Comment by Electroid** [comment]
I have deployed an experimental change to enable stale-while-revalidate. This means that if there is a 429 error, instead of serving that error, it will serve the last known response and retry again in the background. I'll monitor results this week.

**Comment by kyngs** [comment]
> The reason for the increased `429`s actually appears to be because someone is sending 60 million requests per day, hogging up the rate limits. (this is way way above anyone else)
> 
> I've limited the IP, so errors should start to reduce.

I honestly wonder who would want to spam a service like this

**Comment by Electroid** [comment]
It appears people want the ability to be notified when a username becomes available or a profile changes. That is why there are a large volume of requests. I'm thinking of introducing a webhook or websocket API where you can subscribe to changes.

**Comment by AoElite** [comment]
@Electroid Cloudflare recently added free rate limiting rules. Maybe you should set up a very lenient rate limit rule to prevent this from happening in extreme cases.

**Comment by kyngs** [comment]
> It appears people want the ability to be notified when a username becomes available or a profile changes. That is why there are a large volume of requests. I'm thinking of introducing a webhook or websocket API where you can subscribe to changes.

I mean, how would you implement that on your side tho? There's nothing like this available from Mojang I'm aware of

**Comment by Electroid** [comment]
> @Electroid Cloudflare recently added free rate limiting rules. Maybe you should set up a very lenient rate limit rule to prevent this from happening in extreme cases.

Yes, I have done this now. It's still generous, but will monitor and adjust.

**Comment by andreasdc** [comment]
Still too many requests

**Comment by eyezahhhh** [comment]
It seems to work if I give it a UUID, but giving a username makes it return a 429 error. MCHeads has the same issue right now.

**Comment by andreasdc** [comment]
All cloudflare workers are blocked by mojang, I think it's good to report it to cloudflare.

**Comment by Electroid** [comment]
> It seems to work if I give it a UUID, but giving a username makes it return a 429 error. MCHeads has the same issue right now.

Yes, it appears that the `username -> uuid` endpoint is more impacted by the rate limits. I am still working on solutions. While there is still elevated 429s, it is starting to come down as more profiles become cached.

**Comment by andreasdc** [comment]
All cloudflare workers are affected, without reporting it to cf not much will help.

**Comment by Electroid** [comment]
> All cloudflare workers are affected, without reporting it to cf not much will help.

Cloudflare can't do anything here, Mojang rate-limits by IP address, and Cloudflare does not allow you to configure the egress IP.

I still see lots `200` and `404` responses from my logs.

**Comment by andreasdc** [comment]
200 = premium 404 = nopremium
Cliudflare has limited powers of cloudflare workers, for example I have another worker running with mojang api and it's rate limited all the time since 2 days, that means somewhere is massive spam from workers to mojang, which results in blockage of all workers.
If cf won't limit bad movement or won't add more ip addresses, it won't be fixed.

**Comment by Electroid** [comment]
Okay, I've made a change where if there is a 429 from Cloudflare it will fallback to another server running on `fly.io`. I've already seen a massive reduction in errors.

**Comment by Electroid** [comment]
Issue is now resolved! 🎉
