### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by NicklasMatzulla** [Electroid/mojang-api#64]
Good day,
I have tried to upload the project on my website. The problem is that when I make a request I get the following error:
```
{
  "code": 500,
  "error": "Internal Error",
  "reason": "ReferenceError: NAMES is not defined\n    at w (worker.js:19:104323)\n    at b (worker.js:19:104654)\n    at s (worker.js:19:113568)\n    at n (worker.js:19:113460)\n    at i (worker.js:19:113155)\n    at worker.js:19:113095"
}
```

I uploaded the project via wrangler publish directly, I hope this is not a problem. I also made some changes to the wrangler.toml file:
```
name = "mojangapi"
compatibility_date = "2022-12-24"
account_id = "26aec3e9da0093e5af447caabfb1a4f7"
zone_id = "474b68bd5f1ca76edc6260d8af7cd390"
routes = [
    "api.limitcore.net/mojang/v2*"
]
workers_dev = false
main = "dist/worker.js"
[build]
command = "npm run build"
```

The reason I don't build the project with wrangler before is because doing so gives the following error:
https://just-paste.it/l7EgQlXStb

I hope you can help me.

With kind regards
Nicklas Matzulla

**Comment by Electroid** [comment]
Hi there,

You need to create KV namespaces:

```toml
kv_namespaces = [
    { binding = "USERS", id = "ba64684b6f3c44778748d3e3010a81dd", preview_id = "ba64684b6f3c44778748d3e3010a81dd" },
    { binding = "NAMES", id = "f4e19fdf2b2c43d4869071de5e1c59f8", preview_id = "f4e19fdf2b2c43d4869071de5e1c59f8" },
    { binding = "BIRTHDAYS", id = "297276ad8bd3474b8344558da7f8e5f0", preview_id = "297276ad8bd3474b8344558da7f8e5f0" },
    { binding = "AVATARS", id = "360dd7a808454c228457118f18ee4a88", preview_id = "360dd7a808454c228457118f18ee4a88" }
]
```

The IDs listed above are mine, but if you want to deploy this yourself, you will need to create 4 KV namespaces and replace the IDs with your own.

https://egghead.io/lessons/cloudflare-create-a-cloudflare-workers-kv-namespace
