### ISSUE TITLE
Skin is not updated for over 1 month

### ISSUE THREAD

**Issue by xknat** [Electroid/mojang-api#70]
Hey there!
We are recieving multiple complains from users about skins not being "up to date'.
One user even had a month old skin:
ign: **Redwolf_Ahri**
uuid: **6ddebd2057bc4a87a54ebff26689be89**

mojang provided values: (https://sessionserver.mojang.com/session/minecraft/profile/6ddebd2057bc4a87a54ebff26689be89?unsigned=false)
`ewogICJ0aW1lc3RhbXAiIDogMTY3NTAwOTc4NjQ0OSwKICAicHJvZmlsZUlkIiA6ICI2ZGRlYmQyMDU3YmM0YTg3YTU0ZWJmZjI2Njg5YmU4OSIsCiAgInByb2ZpbGVOYW1lIiA6ICJSZWR3b2xmX0FocmkiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTgzNWQwYmQ5NzU0ZTIwMzkxY2VhYmJlMmI1ZDliYzU1M2I1MzVjNDMwYWY5NjEwMTYyZGZjZmY2NjBmMmI5MyIKICAgIH0KICB9Cn0=`
Texture: 

ashcon provided values: (https://api.ashcon.app/mojang/v2/user/6ddebd2057bc4a87a54ebff26689be89)
(same as https://api.ashcon.app/mojang/v2/user/Redwolf_Ahri)
`ewogICJ0aW1lc3RhbXAiIDogMTY3MTk4NjYyODY5OSwKICAicHJvZmlsZUlkIiA6ICI2ZGRlYmQyMDU3YmM0YTg3YTU0ZWJmZjI2Njg5YmU4OSIsCiAgInByb2ZpbGVOYW1lIiA6ICJTaW1hb1ZpbGFzMDEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMThlY2JhYzBmNWE0NjI1YzYzNDRkNWJkY2FlNTg2ZTg2NzMwYWZiYjZlNjEyYWIzZjc4MjFhOGViZDcwZGE4OSIKICAgIH0KICB9Cn0=`

**Comment by xknat** [comment]
Issue seems to be resolved.

**Comment by adamk33n3r** [comment]
Mine hasn't been updated in over a week.
