### ISSUE TITLE
Seems to not work, returns forbidden for requests

### ISSUE THREAD

**Issue by kyngs** [Electroid/mojang-api#80]
![image](https://github.com/Electroid/mojang-api/assets/38181667/36983351-76a6-438c-afeb-c0f94a69e9dc)
Trying Notch works tho.

**Comment by Electroid** [comment]
Investigating.

**Comment by Electroid** [comment]
I deployed a potential fix, let me know if you're still experiencing issues.

**Comment by kyngs** [comment]
I've tested it out and I still seem to be getting the same forbidden error when I try to check my nickname.

**Comment by kyngs** [comment]
My nick now seems to resolve correctly, perhaps yesterday the error was still stuck in cache.
